ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.anand88b.online
CATALOGUE_HOST: catalogue-dev.anand88b.online
REDIS_HOST: redis-dev.anand88b.online
USER_HOST: user-dev.anand88b.online
CART_HOST: cart-dev.anand88b.online
MYSQL_HOST: mysql-dev.anand88b.online
SHIPPING_HOST: shipping-dev.anand88b.online
RABBITMQ_HOST: rabbitmq-dev.anand88b.online
PAYMENT_HOST: payment-dev.anand88b.online